apiVersion: batch/v1
kind: Job
metadata:
  name: pi
  namespace: default
spec:
  parallelism: 6
  completions: 6
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
        resources:
          requests:
            cpu: 100m
      restartPolicy: Never
